#!/bin/bash -v

# This script runs on instances with a node_type tag of "hadoop-dn"
# It sets the roles that determine what software is installed
# on this instance by platform-salt scripts and the minion
# id and hostname

# The pnda_env-<cluster_name>.sh script generated by the CLI should
# be run prior to running this script to define various environment
# variables

# Parameters:
#  $1 - node index for this datanode - as this node type may be horizontally scaled, should start at 0.

set -e

# The hadoop:role grain is used by the cm_setup.py (in platform-salt) script to
# place specific hadoop roles on this instance.
# The mapping of hadoop roles to hadoop:role grains is
# defined in the cfg_<flavor>.py.tpl files (in platform-salt)
cat >> /etc/salt/grains <<EOF
hadoop:
  role: DATANODE
EOF

cat >> /etc/salt/minion <<EOF
id: $PNDA_CLUSTER-hadoop-dn-$1
EOF

# list of mountpoints to assign to volumes in decreasing size order
# mountpoint filesystem
mkdir -p /etc/pnda/disk-config
cat > /etc/pnda/disk-config/requested-volumes <<EOF
/data0 xfs
/var/log/pnda xfs
EOF

echo $PNDA_CLUSTER-hadoop-dn-$1 > /etc/hostname
hostname $PNDA_CLUSTER-hadoop-dn-$1

service salt-minion restart
